image: nixos/25.05
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
sources:
  - https://git.sr.ht/~alexdavid/jail.nix
tasks:
  - setup: "sudo ln -s /etc/zoneinfo/EST /etc/localtime"
  - test-jail-nix: "cd jail.nix && nix run ./tests#runTests"
  - check-format: "cd jail.nix && nix run ./tests#checkFmt"
  - build-website: "cd jail.nix && nix build -L ./website#default"
