image: nixos/25.05
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - test-jail-nix: "cd jail.nix/tests && nix run .#runTests"
  - check-format: "cd jail.nix/tests && nix run .#checkFmt"
  - build-website: "cd jail.nix/website && nix build -L .#default"
